package by.htp.ishop.controller.command;

public enum CommandName {

	SIGNIN,
	GO_TO_SIGNIN, 
	SIGNOUT,
	GO_TO_REGISTRATION,
	REGISTRATION,
	GO_TO_MAIN,
	WRONG_REQUEST,
	CHANGELOCAL,
	SUBCATEGORY,
	GROUP_PRODUCT_BY_SUBCATEGORY,
	GO_TO_PRODUCT_INFO,
	ADD_TO_CART,
	GO_TO_CART,
	DELETE_PRODUCT_IN_CART,
	GO_TO_CHECKOUT,
	ORDER,
	CHECKOUT,
	GO_TO_ERROR_PAGE,
	ADD_PRODUCT_FAVORITES,
	DELETE_PRODUCT_FAVORITES,
	FAVORITES;
}
